server:
  port: 9696

spring:
  config:
    import: "optional:classpath:.env"
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration-minutes: 60
  refresh-token-expiration-days: 1

logging:
  level:
    liquibase: DEBUG                # детали работы Liquibase (включая контрольные суммы)
    org.springframework.jdbc: DEBUG # SQL, выполняемый через JdbcTemplate (если используется)
    org.hibernate.SQL: DEBUG        # вывод SQL-запросов Hibernate (уже включено show-sql, но этот уровень даст больше)
    org.hibernate.orm.jdbc.bind: TRACE  # печатает значения параметров запросов
    org.springframework.transaction: DEBUG  # информация о транзакциях